package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"templcn/docs-site/views"
)

var adapted = map[string]string{
	"calendar":    "Go-native date state + vanilla runtime",
	"carousel":    "templ composition + vanilla runtime",
	"chart":       "TanStack Charts enhancement + SVG fallback",
	"combobox":    "searchable native/listbox enhancement",
	"command":     "searchable native/listbox enhancement",
	"data-table":  "server HTML + TanStack Table enhancement",
	"date-picker": "server-rendered date values + vanilla runtime",
	"drawer":      "templ composition + vanilla runtime",
	"sonner":      "DOM event/toast runtime",
	"toast":       "DOM event/toast runtime",
}

var interactive = map[string]bool{
	"accordion": true, "alert-dialog": true, "calendar": true, "carousel": true,
	"checkbox": true, "combobox": true, "command": true, "context-menu": true,
	"date-picker": true, "dialog": true, "drawer": true, "dropdown-menu": true,
	"hover-card": true, "input-otp": true, "menubar": true, "navigation-menu": true,
	"popover": true, "radio-group": true, "resizable": true, "select": true,
	"sheet": true, "sidebar": true, "slider": true, "sonner": true, "switch": true,
	"tabs": true, "toggle-group": true, "toast": true, "tooltip": true,
}

var browserEvidence = map[string]string{
	"alert-dialog":    "dialog-family-runtime.spec.ts",
	"calendar":        "calendar-runtime.spec.ts",
	"carousel":        "longtail-runtime.spec.ts",
	"checkbox":        "longtail-runtime.spec.ts",
	"context-menu":    "menu-family-runtime.spec.ts",
	"date-picker":     "calendar-runtime.spec.ts",
	"drawer":          "dialog-family-runtime.spec.ts",
	"hover-card":      "floating-runtime.spec.ts",
	"input-otp":       "form-controls-runtime.spec.ts",
	"menubar":         "menu-family-runtime.spec.ts",
	"navigation-menu": "menu-family-runtime.spec.ts",
	"popover":         "floating-runtime.spec.ts",
	"radio-group":     "form-controls-runtime.spec.ts",
	"resizable":       "longtail-runtime.spec.ts",
	"sheet":           "dialog-family-runtime.spec.ts",
	"sidebar":         "longtail-runtime.spec.ts",
	"slider":          "form-controls-runtime.spec.ts",
	"sonner":          "longtail-runtime.spec.ts",
	"switch":          "longtail-runtime.spec.ts",
	"toast":           "longtail-runtime.spec.ts",
	"toggle-group":    "form-controls-runtime.spec.ts",
	"tabs":            "tabs-runtime.spec.ts",
	"tooltip":         "floating-runtime.spec.ts",
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	uiRoot := filepath.Join(root, "..", "ui")
	output := filepath.Join(root, "..", "docs", "V1_COMPONENT_MATRIX.md")

	docs := views.ComponentIndex()
	sort.Slice(docs, func(i, j int) bool { return docs[i].Slug < docs[j].Slug })

	var b strings.Builder
	b.WriteString("<!-- Generated by docs-site/cmd/matrix. Do not edit manually. -->\n")
	b.WriteString("# v1 component matrix\n\n")
	b.WriteString("Statuses are generated from the component docs index, UI source tree, and repository test inventory. `intentional difference` records an explicit Go-native adaptation.\n\n")
	b.WriteString("| Item | Implemented | Documented | Installable | Preview | Keyboard/a11y | Intentional difference |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, doc := range docs {
		source := filepath.Join(uiRoot, strings.ReplaceAll(doc.Slug, "-", "_")+".go")
		if doc.Slug == "data-table" {
			source = filepath.Join(uiRoot, "datatable.go")
		}
		implemented := fileExists(source)
		tested := testEvidence(root, doc.Slug)
		keyboard := "not applicable"
		if interactive[doc.Slug] {
			keyboard = "pending browser evidence"
			if tested {
				keyboard = "covered by tests"
			}
		}
		difference := adapted[doc.Slug]
		if difference == "" {
			difference = "none recorded"
		}
		apiDocumented := len(doc.APIProps) > 0 || strings.Contains(doc.GoUsage, "Props{")
		documented := strings.TrimSpace(doc.Install) == "templcn add "+doc.Slug && strings.TrimSpace(doc.GoUsage) != "" && apiDocumented && len(doc.Examples) > 0
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n", doc.Slug, check(implemented), check(documented), check(strings.TrimSpace(doc.Install) == "templcn add "+doc.Slug), check(len(doc.Examples) > 0), keyboard, difference)
	}

	if err := os.WriteFile(output, []byte(b.String()), 0644); err != nil {
		panic(err)
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func testEvidence(root, slug string) bool {
	if evidence, ok := browserEvidence[slug]; ok {
		return fileExists(filepath.Join(root, "tests", evidence))
	}
	needle := strings.ReplaceAll(slug, "-", "")
	entries, err := os.ReadDir(filepath.Join(root, "tests"))
	if err != nil {
		return false
	}
	for _, entry := range entries {
		name := strings.ToLower(strings.ReplaceAll(entry.Name(), "-", ""))
		if strings.Contains(name, needle) {
			return true
		}
	}
	return false
}

func check(ok bool) string {
	if ok {
		return "yes"
	}
	return "no"
}
