// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "bytes"
import "context"
import "io"

import "github.com/a-h/templ"
import "shadcn/ui"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuffer := w.(*bytes.Buffer)
		if !isBuffer {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		ctx = templ.ClearChildren(ctx)

		body := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			buf, isBuffer := w.(*bytes.Buffer)
			if !isBuffer {
				buf = templ.GetBuffer()
				defer templ.ReleaseBuffer(buf)
			}
			_, err = buf.WriteString("<main class=\"min-h-svh\"><section class=\"mx-auto flex min-h-svh max-w-4xl flex-col items-start justify-center gap-6 px-6 py-24\">")
			if err != nil {
				return err
			}
			err = ui.Badge(ui.BadgeProps{
				Label:   "PR 0 foundation",
				Variant: ui.BadgeVariantOutline,
			}).Render(ctx, buf)
			if err != nil {
				return err
			}
			_, err = buf.WriteString("<div class=\"max-w-2xl space-y-4\"><h1 class=\"text-4xl font-semibold tracking-tight text-foreground sm:text-6xl\">A shadcn-style foundation for Go.</h1><p class=\"max-w-xl text-base leading-7 text-muted-foreground sm:text-lg\">PR 0 establishes the shared tokens, Tailwind v4 pipeline, and a real `ui` package so later component PRs can stay close to the upstream shadcn experience.</p></div><div class=\"flex flex-wrap gap-3\">")
			if err != nil {
				return err
			}
			err = ui.Button(ui.ButtonProps{
				Label:   "Start with the foundation",
				Variant: ui.ButtonVariantDefault,
				Size:    ui.ButtonSizeDefault,
				Type:    "button",
			}).Render(ctx, buf)
			if err != nil {
				return err
			}
			err = ui.Button(ui.ButtonProps{
				Label:   "Read the guide",
				Variant: ui.ButtonVariantOutline,
				Size:    ui.ButtonSizeDefault,
				DOMProps: ui.DOMProps{
					Element: "a",
				},
				Href: "/docs/shadcn-templ-implementation-guide.md",
			}).Render(ctx, buf)
			if err != nil {
				return err
			}
			_, err = buf.WriteString("</div></section></main>")
			if err != nil {
				return err
			}
			if !isBuffer {
				_, err = buf.WriteTo(w)
			}
			return err
		})

		err = Page().Render(templ.WithChildren(ctx, body), buf)
		if err != nil {
			return err
		}
		if !isBuffer {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
