// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "bytes"
import "context"
import "io"

import "github.com/a-h/templ"

func Page() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuffer := w.(*bytes.Buffer)
		if !isBuffer {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		children := templ.GetChildren(ctx)
		if children == nil {
			children = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = buf.WriteString("<!doctype html><html lang=\"en\" class=\"h-full bg-background text-foreground antialiased\"><head><title>shadcn/ui</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"color-scheme\" content=\"light dark\"><link rel=\"stylesheet\" href=\"/public/globals.css\"></head><body class=\"min-h-svh bg-background text-foreground antialiased\">")
		if err != nil {
			return err
		}
		err = children.Render(ctx, buf)
		if err != nil {
			return err
		}
		_, err = buf.WriteString("</body></html>")
		if err != nil {
			return err
		}
		if !isBuffer {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
