package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	assetPath := filepath.Join(root, "..", "docs-site", "public", "tanstack-runtime.js")
	data, err := os.ReadFile(assetPath)
	if err != nil {
		panic(fmt.Errorf("read TanStack runtime: %w", err))
	}

	encoded := base64.StdEncoding.EncodeToString(data)
	output := filepath.Join(root, "runtime_embed.go")
	content := `package main

import "encoding/base64"

const tanstackRuntimeAssetBase64 = ` + fmt.Sprintf("%q", encoded) + `

var tanstackRuntimeAsset = decodeTanStackRuntime()

func decodeTanStackRuntime() string {
	data, err := base64.StdEncoding.DecodeString(tanstackRuntimeAssetBase64)
	if err != nil {
		panic(err)
	}
	return string(data)
}
`
	if err := os.WriteFile(output, []byte(content), 0644); err != nil {
		panic(fmt.Errorf("write embedded runtime: %w", err))
	}

	uiDir := filepath.Join(root, "..", "ui")
	entries, err := os.ReadDir(uiDir)
	if err != nil {
		panic(fmt.Errorf("read UI sources: %w", err))
	}
	paths := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			paths = append(paths, entry.Name())
		}
	}
	sort.Strings(paths)
	var registry strings.Builder
	registry.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage main\n\nvar embeddedRegistrySources = map[string]string{\n")
	for _, name := range paths {
		data, err := os.ReadFile(filepath.Join(uiDir, name))
		if err != nil {
			panic(fmt.Errorf("read UI source %s: %w", name, err))
		}
		fmt.Fprintf(&registry, "\t%q: %s,\n", filepath.ToSlash(filepath.Join("ui", name)), strconv.Quote(string(data)))
	}
	registry.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(root, "registry_sources_embed.go"), []byte(registry.String()), 0644); err != nil {
		panic(fmt.Errorf("write embedded UI sources: %w", err))
	}
}
