package main

import "strings"

func starterMainGo() string {
	return `package main

import (
	"log"
	"net/http"
)

func main() {
	mux := http.NewServeMux()
	mux.Handle("/assets/", http.StripPrefix("/assets/", http.FileServer(http.Dir("assets"))))
	mux.HandleFunc("/", homeHandler)

	log.Println("listening on :8080")
	if err := http.ListenAndServe(":8080", mux); err != nil {
		log.Fatal(err)
	}
}

func homeHandler(w http.ResponseWriter, r *http.Request) {
	if err := Home().Render(r.Context(), w); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`
}

func starterAppTempl(modulePath string) string {
	uiImport := modulePath + "/ui"
	return strings.TrimSpace(`package main

import "` + uiImport + `"

templ Home() {
	<!DOCTYPE html>
	<html lang="en" class="h-full bg-background text-foreground antialiased">
		<head>
			<meta charset="UTF-8"/>
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
			<title>templcn/ui</title>
			<script type="module" src="/assets/runtime.js"></script>
		</head>
		<body class="min-h-svh bg-background text-foreground">
			<main class="mx-auto flex min-h-svh max-w-4xl flex-col justify-center gap-8 px-6 py-16">
				@ui.Card(ui.DOMProps{}) {
					@ui.CardHeader(ui.DOMProps{}) {
						@ui.CardTitle(ui.DOMProps{}) { <span>templcn/ui</span> }
						@ui.CardDescription(ui.DOMProps{}) { <span>Templ-native components copied into your project.</span> }
					}
					@ui.CardContent(ui.DOMProps{}) {
						<div class="flex flex-wrap gap-3">
							@ui.Button(ui.ButtonProps{Label: "Get started"})
							@ui.Button(ui.ButtonProps{Label: "Browse docs", Variant: ui.ButtonVariantOutline, Href: "/docs"})
						</div>
					}
				}
			</main>
		</body>
	</html>
}
`)
}

func starterAppTemplGo(modulePath string) string {
	uiImport := modulePath + "/ui"
	return `// Code generated by templcn init. DO NOT EDIT.

package main

import (
	"context"
	"io"

	"github.com/a-h/templ"
	"` + uiImport + `"
)

func Home() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, ` + "`" + `<!DOCTYPE html>
<html lang="en" class="h-full bg-background text-foreground antialiased">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>templcn/ui</title>
    <script type="module" src="/assets/runtime.js"></script>
  </head>
  <body class="min-h-svh bg-background text-foreground">
    <main class="mx-auto flex min-h-svh max-w-4xl flex-col justify-center gap-8 px-6 py-16">
` + "`" + `)
		if err != nil {
			return err
		}
		if err := ui.Card(ui.DOMProps{}).Render(templ.WithChildren(ctx, templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
			if err := ui.CardHeader(ui.DOMProps{}).Render(templ.WithChildren(ctx, templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
				if err := ui.CardTitle(ui.DOMProps{}).Render(templ.WithChildren(ctx, templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
					_, err := io.WriteString(w, "<span>templcn/ui</span>")
					return err
				})), w); err != nil {
					return err
				}
				return ui.CardDescription(ui.DOMProps{}).Render(templ.WithChildren(ctx, templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
					_, err := io.WriteString(w, "<span>Templ-native components copied into your project.</span>")
					return err
				})), w)
			})), w); err != nil {
				return err
			}
			return ui.CardContent(ui.DOMProps{}).Render(templ.WithChildren(ctx, templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
				if _, err := io.WriteString(w, "<div class=\"flex flex-wrap gap-3\">"); err != nil {
					return err
				}
				if err := ui.Button(ui.ButtonProps{Label: "Get started"}).Render(ctx, w); err != nil {
					return err
				}
				if err := ui.Button(ui.ButtonProps{Label: "Browse docs", Variant: ui.ButtonVariantOutline, Href: "/docs"}).Render(ctx, w); err != nil {
					return err
				}
				_, err := io.WriteString(w, "</div>")
				return err
			})), w)
		})), w); err != nil {
			return err
		}
		_, err = io.WriteString(w, ` + "`" + `
    </main>
  </body>
</html>` + "`" + `)
		return err
	})
}
`
}

func starterCSS() string {
	return `@import "tailwindcss";

@source "./**/*.go";
@source "./**/*.templ";

@custom-variant dark (&:is(.dark *));

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --radius-sm: calc(var(--radius) * 0.6);
  --radius-md: calc(var(--radius) * 0.8);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) * 1.4);
  --radius-2xl: calc(var(--radius) * 1.8);
  --radius-3xl: calc(var(--radius) * 2.2);
  --radius-4xl: calc(var(--radius) * 2.6);
}

:root {
  --radius: 0.625rem;
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --destructive-foreground: oklch(0.985 0 0);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.922 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --destructive-foreground: oklch(0.985 0 0);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.556 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(1 0 0 / 10%);
  --sidebar-ring: oklch(0.556 0 0);
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }

  body {
    @apply bg-background text-foreground;
  }
}
`
}

func starterRuntimeJS() string {
	return `/**
 * templcn JS runtime
 *
 * Starter projects get a bundled runtime. The docs site keeps the same behavior
 * split into component modules under /public/runtime/.
 */

const floatingRoots = '[data-slot="popover"], [data-slot="hover-card"], [data-slot="tooltip"], [data-slot="select"], [data-slot="combobox"], [data-slot="dropdown-menu"], [data-slot="context-menu"], [data-slot="menubar"], [data-slot="navigation-menu"], [data-dropdown-menu-root]';
const floatingContent = '[data-slot$="-content"], [data-dropdown-menu-content]';
const dialogTriggers = '[data-slot="dialog-trigger"], [data-slot="sheet-trigger"], [data-slot="drawer-trigger"], [data-slot="alert-dialog-trigger"]';
const dialogClose = '[data-slot$="-close"], [data-slot="alert-dialog-action"], [data-slot="alert-dialog-cancel"]';
const selectableRoots = '[data-slot="select"], [data-slot="combobox"]';
const selectableItems = '[data-slot="select-item"], [data-slot="combobox-item"], [role="option"]';
const commandRoot = '[data-slot="command"]';
const commandInput = '[data-slot="command-input"]';
const commandItem = '[data-slot="command-item"]';
const commandEmpty = '[data-slot="command-empty"]';
const radioGroups = '[data-slot="radio-group"]';
const toggleGroups = '[data-slot="toggle-group"]';
const sliderRoots = '[data-slot="slider"]';
const calendarRoot = '[data-slot="calendar"]';
const calendarDayButton = '[data-slot="calendar-day-button"]';
const calendarMonthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const calendarWeekdays = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];
const checkedInputs = '[data-slot="checkbox"], [data-slot="switch"]';
const inputOTPRoot = '[data-slot="input-otp"]';
const carouselRoot = '[data-slot="carousel"]';
const resizableRoot = '[data-slot="resizable-panel-group"]';
const toastRoot = '[data-slot="toast"]';
const sidebarProvider = '[data-slot="sidebar-provider"]';
const datePickerRoot = '[data-slot="date-picker"]';
const typeahead = new WeakMap();

function isOpen(root) {
  return root?.getAttribute('data-open') === 'true' || root?.hasAttribute('open');
}

function contentFor(root) {
  return root?.querySelector(floatingContent);
}

function triggerFor(root) {
  return root?.querySelector('[data-slot$="-trigger"], [data-dropdown-menu-trigger], [aria-haspopup]');
}

function setOpen(root, open, trigger = triggerFor(root)) {
  const content = contentFor(root);
  root.toggleAttribute('open', open && root.tagName === 'DETAILS');
  root.setAttribute('data-state', open ? 'open' : 'closed');
  if (open) root.setAttribute('data-open', 'true');
  else root.removeAttribute('data-open');
  trigger?.setAttribute('aria-expanded', open ? 'true' : 'false');
  trigger?.setAttribute('data-state', open ? 'open' : 'closed');
  content?.setAttribute('data-state', open ? 'open' : 'closed');
  if (content) content.toggleAttribute('hidden', !open);
  if (open) positionFloating(root);
}

function positionFloating(root) {
  const trigger = triggerFor(root);
  const content = contentFor(root);
  if (!trigger || !content) return;
  content.style.position = 'fixed';
  content.style.margin = '0';
  content.style.zIndex ||= '50';
  const side = root.getAttribute('data-side') || content.getAttribute('data-side') || 'bottom';
  const align = root.getAttribute('data-align') || content.getAttribute('data-align') || 'center';
  const offset = Number.parseFloat(root.getAttribute('data-side-offset') || '4') || 4;
  const anchor = trigger.getBoundingClientRect();
  const rect = content.getBoundingClientRect();
  let left = align === 'start' ? anchor.left : align === 'end' ? anchor.right - rect.width : anchor.left + (anchor.width - rect.width) / 2;
  let top = side === 'top' ? anchor.top - rect.height - offset : anchor.bottom + offset;
  left = Math.max(8, Math.min(left, window.innerWidth - rect.width - 8));
  top = Math.max(8, Math.min(top, window.innerHeight - rect.height - 8));
  content.style.left = Math.round(left) + 'px';
  content.style.top = Math.round(top) + 'px';
  content.setAttribute('data-side', side);
  content.setAttribute('data-align', align);
  content.style.setProperty('--anchor-width', anchor.width + 'px');
  content.style.setProperty('--anchor-height', anchor.height + 'px');
  content.style.setProperty('--radix-popover-trigger-width', anchor.width + 'px');
  content.style.setProperty('--radix-dropdown-menu-trigger-width', anchor.width + 'px');
}

function focusable(root) {
  return Array.from(root.querySelectorAll('a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])')).filter((el) => !el.hidden);
}

function openFloatingRoots() {
  return Array.from(document.querySelectorAll(floatingRoots)).filter((root) => root.getAttribute('data-open') === 'true');
}

function moveItemFocus(root, direction) {
  const items = focusable(root).filter((el) => el.matches(selectableItems + ', [data-slot$="-item"], [data-dropdown-menu-item]'));
  if (!items.length) return false;
  const current = items.indexOf(document.activeElement);
  const next = current === -1 ? (direction > 0 ? 0 : items.length - 1) : (current + direction + items.length) % items.length;
  items[next].focus();
  items.forEach((item) => item.removeAttribute('data-highlighted'));
  items[next].setAttribute('data-highlighted', '');
  return true;
}

function syncSelectValue(root) {
  const value = root.getAttribute('data-value') || root.getAttribute('data-default-value') || '';
  if (!value) return;
  root.setAttribute('data-value', value);
  const item = Array.from(root.querySelectorAll(selectableItems)).find((option) => option.getAttribute('data-value') === value);
  const display = root.querySelector('[data-slot="select-value"], [data-slot="combobox-value"]');
  if (item) {
    item.setAttribute('aria-selected', 'true');
    item.setAttribute('data-state', 'checked');
    if (display && !display.textContent.trim()) display.textContent = item.textContent.trim();
  }
  const name = root.getAttribute('data-name');
  if (name) {
    let input = root.querySelector('input[type="hidden"][name="' + CSS.escape(name) + '"]');
    if (!input) {
      input = document.createElement('input');
      input.type = 'hidden';
      input.name = name;
      root.appendChild(input);
    }
    input.value = value;
  }
}

function focusByTypeahead(root, key) {
  const previous = typeahead.get(root) || { value: '', expires: 0 };
  const now = Date.now();
  const value = (now > previous.expires ? '' : previous.value) + key.toLocaleLowerCase();
  typeahead.set(root, { value, expires: now + 700 });
  const items = Array.from(root.querySelectorAll(selectableItems)).filter((item) => !item.disabled && item.getAttribute('aria-disabled') !== 'true');
  const match = items.find((item) => item.textContent.trim().toLocaleLowerCase().startsWith(value));
  if (match) {
    items.forEach((item) => item.removeAttribute('data-highlighted'));
    match.setAttribute('data-highlighted', '');
    match.focus();
  }
}

function filterCommand(root, query) {
  const normalized = query.trim().toLocaleLowerCase();
  let visible = 0;
  root.querySelectorAll(commandItem).forEach((item) => {
    const disabled = item.disabled || item.getAttribute('aria-disabled') === 'true';
    const matches = !normalized || item.textContent.trim().toLocaleLowerCase().includes(normalized);
    item.toggleAttribute('hidden', !matches);
    item.setAttribute('aria-selected', 'false');
    if (!disabled && matches) visible += 1;
  });
  root.querySelectorAll(commandEmpty).forEach((empty) => empty.toggleAttribute('hidden', visible !== 0));
}

function syncCommand(root) {
  filterCommand(root, root.querySelector(commandInput)?.value || '');
}

function syncRadioGroup(root) {
  const checked = root.querySelector('[data-slot="radio-group-item"] input[type="radio"]:checked');
  if (checked) root.setAttribute('data-value', checked.value);
  root.querySelectorAll('[data-slot="radio-group-item"]').forEach((item) => {
    const input = item.querySelector('input[type="radio"]');
    const selected = input?.checked === true;
    item.setAttribute('data-state', selected ? 'checked' : 'unchecked');
    item.setAttribute('aria-checked', selected ? 'true' : 'false');
  });
}

function setToggleItem(item, on) {
  item.setAttribute('data-state', on ? 'on' : 'off');
  item.setAttribute('aria-pressed', on ? 'true' : 'false');
}

function syncToggleGroup(root) {
  const values = Array.from(root.querySelectorAll('[data-slot="toggle-group-item"][data-state="on"]')).map((item) => item.getAttribute('data-value')).filter(Boolean);
  root.setAttribute('data-value', values.join(' '));
}

function syncSlider(root) {
  const input = root.querySelector('input[type="range"]');
  if (!input) return;
  root.setAttribute('data-value', input.value);
  input.setAttribute('aria-valuenow', input.value);
}

function syncCalendar(root) {
  const current = parseCalendarMonth(root.getAttribute('data-current-month'));
  root.setAttribute('data-current-month', formatCalendarMonth(current));
  const caption = root.querySelector('[data-slot="calendar-caption"]');
  if (caption) caption.textContent = calendarMonthNames[current.getUTCMonth()] + ' ' + current.getUTCFullYear();
  let months = root.querySelector('[data-slot="calendar-months"]');
  if (!months) {
    months = document.createElement('div');
    months.setAttribute('data-slot', 'calendar-months');
    months.className = 'flex flex-col gap-4 sm:flex-row';
    root.appendChild(months);
  }
  months.innerHTML = '';
  months.appendChild(renderCalendarMonth(root, current));
}

function shiftCalendarMonth(root, delta) {
  const date = parseCalendarMonth(root.getAttribute('data-current-month'));
  date.setUTCMonth(date.getUTCMonth() + delta);
  root.setAttribute('data-current-month', formatCalendarMonth(date));
  syncCalendar(root);
}

function renderCalendarMonth(root, month) {
  const wrapper = document.createElement('div');
  wrapper.setAttribute('data-slot', 'calendar-month');
  wrapper.className = 'space-y-2';
  const grid = document.createElement('div');
  grid.setAttribute('data-slot', 'calendar-grid');
  grid.setAttribute('role', 'grid');
  grid.setAttribute('aria-label', calendarMonthNames[month.getUTCMonth()] + ' ' + month.getUTCFullYear());
  grid.className = 'space-y-1';
  const header = document.createElement('div');
  header.setAttribute('role', 'row');
  header.className = root.getAttribute('data-show-week-number') === 'true' ? 'grid grid-cols-8 gap-1' : 'grid grid-cols-7 gap-1';
  if (root.getAttribute('data-show-week-number') === 'true') {
    const weekHeader = document.createElement('div');
    weekHeader.setAttribute('role', 'columnheader');
    weekHeader.setAttribute('aria-label', 'Week number');
    weekHeader.className = 'flex size-(--cell-size) items-center justify-center text-xs text-muted-foreground';
    header.appendChild(weekHeader);
  }
  calendarWeekdays.forEach((weekday) => {
    const cell = document.createElement('div');
    cell.setAttribute('role', 'columnheader');
    cell.className = 'flex size-(--cell-size) items-center justify-center text-xs text-muted-foreground';
    cell.textContent = weekday;
    header.appendChild(cell);
  });
  grid.appendChild(header);
  const start = new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth(), 1 - month.getUTCDay()));
  for (let week = 0; week < 6; week += 1) {
    const row = document.createElement('div');
    row.setAttribute('role', 'row');
    row.className = root.getAttribute('data-show-week-number') === 'true' ? 'grid grid-cols-8 gap-1' : 'grid grid-cols-7 gap-1';
    if (root.getAttribute('data-show-week-number') === 'true') {
      const weekNumber = document.createElement('div');
      weekNumber.setAttribute('data-slot', 'calendar-week-number');
      weekNumber.className = 'flex size-(--cell-size) items-center justify-center text-xs text-muted-foreground';
      weekNumber.textContent = String(week + 1).padStart(2, '0');
      row.appendChild(weekNumber);
    }
    for (let day = 0; day < 7; day += 1) {
      row.appendChild(renderCalendarDay(root, month, addCalendarDays(start, week * 7 + day)));
    }
    grid.appendChild(row);
  }
  wrapper.appendChild(grid);
  return wrapper;
}

function renderCalendarDay(root, month, date) {
  const value = formatCalendarDate(date);
  const selected = (root.getAttribute('data-selected') || '').split(/[,\s]+/).includes(value);
  const outside = date.getUTCMonth() !== month.getUTCMonth();
  const cell = document.createElement('div');
  cell.setAttribute('role', 'gridcell');
  cell.setAttribute('data-day', value);
  cell.className = 'relative p-0 text-center text-sm focus-within:relative focus-within:z-20';
  if (outside) cell.setAttribute('data-outside', 'true');
  if (selected) cell.setAttribute('data-selected', 'true');
  const button = document.createElement('button');
  button.type = 'button';
  button.setAttribute('data-slot', 'calendar-day-button');
  button.setAttribute('data-date', value);
  button.setAttribute('data-day', date.toLocaleDateString(root.getAttribute('data-locale') || undefined, { timeZone: 'UTC' }));
  button.setAttribute('aria-label', date.toLocaleDateString(root.getAttribute('data-locale') || undefined, { dateStyle: 'long', timeZone: 'UTC' }));
  button.setAttribute('aria-selected', selected ? 'true' : 'false');
  button.className = 'inline-flex size-(--cell-size) items-center justify-center rounded-md text-sm font-normal tabular-nums hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-40 aria-selected:bg-primary aria-selected:text-primary-foreground data-[today=true]:bg-accent data-[today=true]:text-accent-foreground data-[outside=true]:text-muted-foreground data-[outside=true]:opacity-50';
  button.textContent = String(date.getUTCDate());
  if (selected) button.setAttribute('data-selected', 'true');
  if (outside) button.setAttribute('data-outside', 'true');
  if (value === formatCalendarDate(new Date())) button.setAttribute('data-today', 'true');
  if (outside && root.getAttribute('data-show-outside-days') === 'false') button.hidden = true;
  cell.appendChild(button);
  return cell;
}

function parseCalendarMonth(value) {
  const parts = (value || new Date().toISOString().slice(0, 7)).split('-').map(Number);
  return new Date(Date.UTC(parts[0], parts[1] - 1, 1));
}

function addCalendarDays(date, days) {
  const next = new Date(date);
  next.setUTCDate(next.getUTCDate() + days);
  return next;
}

function formatCalendarMonth(date) {
  return date.getUTCFullYear() + '-' + String(date.getUTCMonth() + 1).padStart(2, '0');
}

function formatCalendarDate(date) {
  return date.getUTCFullYear() + '-' + String(date.getUTCMonth() + 1).padStart(2, '0') + '-' + String(date.getUTCDate()).padStart(2, '0');
}

function syncCheckedInput(input) {
  input.setAttribute('data-state', input.checked ? 'checked' : 'unchecked');
  input.setAttribute('aria-checked', input.checked ? 'true' : 'false');
}

function syncOTP(root) {
  const slots = Array.from(root.querySelectorAll('[data-slot="input-otp-slot"]'));
  const value = slots.map((slot) => slot.textContent.trim()).join('');
  root.setAttribute('data-value', value);
  const input = root.querySelector('input[type="hidden"]');
  if (input) input.value = value;
}

function syncCarousel(root) {
  const slides = Array.from(root.querySelectorAll('[data-slot="carousel-item"]'));
  const index = Math.max(0, Math.min(Number.parseInt(root.getAttribute('data-index') || root.getAttribute('data-start-index') || '0', 10), slides.length - 1));
  root.setAttribute('data-index', String(index));
  slides.forEach((slide, slideIndex) => {
    slide.toggleAttribute('hidden', slideIndex !== index);
    slide.setAttribute('aria-hidden', slideIndex === index ? 'false' : 'true');
  });
}

function moveCarousel(root, direction) {
  const slides = root.querySelectorAll('[data-slot="carousel-item"]');
  const loop = root.getAttribute('data-loop') === 'true';
  let index = Number.parseInt(root.getAttribute('data-index') || '0', 10) + direction;
  if (loop) index = (index + slides.length) % slides.length;
  else index = Math.max(0, Math.min(index, slides.length - 1));
  root.setAttribute('data-index', String(index));
  syncCarousel(root);
}

function syncResizable(root) {
  root.querySelectorAll('[data-slot="resizable-panel"]').forEach((panel) => {
    const size = Number.parseFloat(panel.getAttribute('data-size') || panel.getAttribute('data-default-size') || '50');
    setPanelSize(panel, size);
  });
}

function setPanelSize(panel, size) {
  panel.setAttribute('data-size', String(Math.round(size * 100) / 100));
  panel.style.flexBasis = size + '%';
}

function clampPanelSize(value, panel) {
  const min = Number.parseFloat(panel.getAttribute('data-min-size') || '5');
  const max = Number.parseFloat(panel.getAttribute('data-max-size') || '95');
  return Math.max(min, Math.min(max, value));
}

function startResizableDrag(event) {
  const handle = event.target.closest('[data-slot="resizable-handle"]');
  const root = handle?.closest(resizableRoot);
  if (!root) return;
  const children = Array.from(root.children);
  const panels = Array.from(root.querySelectorAll('[data-slot="resizable-panel"]'));
  const index = children.indexOf(handle);
  const before = panels.findLast?.((panel) => children.indexOf(panel) < index) || panels[0];
  const after = panels.find((panel) => children.indexOf(panel) > index) || panels[1];
  if (!before || !after) return;
  event.preventDefault();
  const startX = event.clientX;
  const startBefore = Number.parseFloat(before.getAttribute('data-size') || '50');
  const startAfter = Number.parseFloat(after.getAttribute('data-size') || '50');
  const width = root.getBoundingClientRect().width || 1;
  const move = (moveEvent) => {
    const delta = ((moveEvent.clientX - startX) / width) * 100;
    setPanelSize(before, clampPanelSize(startBefore + delta, before));
    setPanelSize(after, clampPanelSize(startAfter - delta, after));
  };
  const up = () => {
    window.removeEventListener('pointermove', move);
    window.removeEventListener('pointerup', up);
  };
  window.addEventListener('pointermove', move);
  window.addEventListener('pointerup', up, { once: true });
}

function syncToast(toast) {
  const open = toast.getAttribute('data-open') === 'true' || toast.getAttribute('data-default-open') === 'true';
  toast.setAttribute('data-state', open ? 'open' : 'closed');
  toast.toggleAttribute('hidden', !open);
}

function closeToast(toast) {
  toast.removeAttribute('data-open');
  toast.setAttribute('data-state', 'closed');
  toast.setAttribute('hidden', '');
}

function setSidebar(root, open) {
  if (open) root.setAttribute('data-open', 'true');
  else root.removeAttribute('data-open');
  root.setAttribute('data-state', open ? 'open' : 'closed');
  root.querySelector('[data-slot="sidebar-trigger"]')?.setAttribute('aria-expanded', open ? 'true' : 'false');
}

function openHoverFloating(event) {
  const trigger = event.target.closest('[data-slot="tooltip-trigger"], [data-slot="hover-card-trigger"]');
  const root = trigger?.closest('[data-slot="tooltip"], [data-slot="hover-card"]');
  if (!root) return;
  setOpen(root, true, trigger);
}

function closeHoverFloating(event) {
  const root = event.target.closest('[data-slot="tooltip"], [data-slot="hover-card"]');
  if (root && !root.contains(event.relatedTarget)) setOpen(root, false);
}

function enabledTabs(root) {
  return Array.from(root.querySelectorAll('[data-slot="tabs-trigger"]')).filter((trigger) => !trigger.disabled && trigger.getAttribute('aria-disabled') !== 'true');
}

function activateTab(trigger) {
  const root = trigger.closest('[data-slot="tabs"], [data-tabs-root]');
  const value = trigger.getAttribute('data-value');
  if (!root || !value) return;
  root.setAttribute('data-value', value);
  root.querySelectorAll('[data-slot="tabs-trigger"]').forEach((candidate) => {
    const active = candidate.getAttribute('data-value') === value;
    candidate.setAttribute('data-state', active ? 'active' : 'inactive');
    candidate.setAttribute('aria-selected', active ? 'true' : 'false');
    candidate.setAttribute('tabindex', active ? '0' : '-1');
  });
  root.querySelectorAll('[data-slot="tabs-content"]').forEach((panel) => {
    const active = panel.getAttribute('data-value') === value;
    panel.setAttribute('data-state', active ? 'active' : 'inactive');
    panel.toggleAttribute('hidden', !active);
  });
}

function syncTabsState(root) {
  const value = root.getAttribute('data-value') || root.getAttribute('data-default-value') || root.querySelector('[data-slot="tabs-trigger"]')?.getAttribute('data-value');
  if (!value) return;
  const trigger = root.querySelector('[data-slot="tabs-trigger"][data-value="' + CSS.escape(value) + '"]');
  if (trigger) activateTab(trigger);
}

function syncDetailsState(details) {
  setOpen(details, details.open, undefined);
  const content = details.querySelector('[data-slot$="-content"]');
  if (content) content.setAttribute('data-state', details.open ? 'open' : 'closed');
}

function syncAccordionDefaults(root) {
  const raw = root.getAttribute('data-value') || root.getAttribute('data-default-value') || '';
  if (!raw) return;
  const values = raw.split(/[\s,]+/).filter(Boolean);
  root.querySelectorAll('[data-slot="accordion-item"]').forEach((item) => {
    item.toggleAttribute('open', values.includes(item.getAttribute('data-value')));
    syncDetailsState(item);
  });
}

function syncAccordion(trigger) {
  const item = trigger.closest('[data-slot="accordion-item"]');
  const root = item?.closest('[data-slot="accordion"]');
  if (!item || !root) return;
  if (item.getAttribute('data-disabled') === 'true') {
    item.removeAttribute('open');
    syncDetailsState(item);
    return;
  }
  if (root.getAttribute('data-type') === 'single' && !item.open) {
    root.querySelectorAll('[data-slot="accordion-item"][open]').forEach((other) => {
      if (other !== item) other.removeAttribute('open');
      syncDetailsState(other);
    });
  }
}

function resolveDialog(trigger) {
  const targetId = trigger.getAttribute('aria-controls') || trigger.getAttribute('data-target');
  if (targetId) return document.getElementById(targetId);
  let next = trigger.nextElementSibling;
  while (next) {
    if (next.tagName === 'DIALOG') return next;
    next = next.nextElementSibling;
  }
  return document.querySelector('dialog');
}

function setDialogState(dialog, open, trigger) {
  trigger ||= triggerForDialog(dialog);
  if (open) {
    dialog.__lastTrigger = trigger || document.activeElement;
    dialog.setAttribute('data-open', 'true');
    dialog.setAttribute('data-state', 'open');
    trigger?.setAttribute('aria-expanded', 'true');
    trigger?.setAttribute('data-state', 'open');
  } else {
    dialog.removeAttribute('data-open');
    dialog.setAttribute('data-state', 'closed');
    const lastTrigger = dialog.__lastTrigger;
    if (lastTrigger && document.contains(lastTrigger)) {
      lastTrigger.setAttribute('aria-expanded', 'false');
      lastTrigger.setAttribute('data-state', 'closed');
    }
  }
  document.querySelectorAll(dialogTriggers).forEach((candidate) => {
    if (candidate === trigger || candidate.getAttribute('aria-controls') === dialog.id || candidate.getAttribute('data-target') === dialog.id) {
      candidate.setAttribute('aria-expanded', open ? 'true' : 'false');
      candidate.setAttribute('data-state', open ? 'open' : 'closed');
    }
  });
  dialog.querySelectorAll('[data-slot$="-content"], [data-slot$="-overlay"]').forEach((el) => {
    el.setAttribute('data-state', open ? 'open' : 'closed');
  });
}

function openDialog(dialog, trigger) {
  const modal = dialog.getAttribute('data-modal') !== 'false';
  if (!dialog.open) {
    if (modal && typeof dialog.showModal === 'function') dialog.showModal();
    else dialog.show();
  }
  setDialogState(dialog, true, trigger);
  const target = focusable(dialog)[0] || dialog.querySelector('[data-slot$="-content"]') || dialog;
  target.focus?.();
}

function closeDialog(dialog) {
  if (dialog.open) dialog.close();
  setDialogState(dialog, false);
  const trigger = dialog.__lastTrigger;
  if (trigger && document.contains(trigger)) trigger.focus();
}

function triggerForDialog(dialog) {
  if (dialog.__lastTrigger && document.contains(dialog.__lastTrigger)) return dialog.__lastTrigger;
  if (!dialog.id) return null;
  return document.querySelector(dialogTriggers + '[aria-controls="' + CSS.escape(dialog.id) + '"]');
}

function initRuntime() {
  document.querySelectorAll('dialog').forEach((dialog) => {
    setDialogState(dialog, dialog.open || dialog.getAttribute('data-open') === 'true');
    dialog.addEventListener('cancel', (event) => {
      event.preventDefault();
      closeDialog(dialog);
    });
    dialog.addEventListener('close', () => setDialogState(dialog, false));
  });
  document.querySelectorAll(floatingRoots).forEach((root) => {
    setOpen(root, isOpen(root));
    if (root.matches(selectableRoots)) syncSelectValue(root);
  });
  document.querySelectorAll(commandRoot).forEach(syncCommand);
  document.querySelectorAll(radioGroups).forEach(syncRadioGroup);
  document.querySelectorAll(toggleGroups).forEach(syncToggleGroup);
  document.querySelectorAll(sliderRoots).forEach(syncSlider);
  document.querySelectorAll(calendarRoot).forEach(syncCalendar);
  document.querySelectorAll(checkedInputs).forEach(syncCheckedInput);
  document.querySelectorAll(inputOTPRoot).forEach(syncOTP);
  document.querySelectorAll(carouselRoot).forEach(syncCarousel);
  document.querySelectorAll(resizableRoot).forEach(syncResizable);
  document.querySelectorAll(toastRoot).forEach(syncToast);
  document.querySelectorAll(sidebarProvider).forEach((root) => setSidebar(root, root.getAttribute('data-open') === 'true' || root.getAttribute('data-default-open') === 'true'));
  document.querySelectorAll('[data-slot="tabs"], [data-tabs-root]').forEach(syncTabsState);
  document.querySelectorAll('[data-slot="accordion"]').forEach(syncAccordionDefaults);
  document.querySelectorAll('[data-slot="accordion-item"], [data-slot="collapsible"]').forEach(syncDetailsState);
  document.addEventListener('toggle', (event) => {
    if (event.target.matches('[data-slot="accordion-item"], [data-slot="collapsible"]')) syncDetailsState(event.target);
  }, true);
  document.addEventListener('click', (event) => {
    const tab = event.target.closest('[data-slot="tabs-trigger"]');
    if (tab) {
      event.preventDefault();
      activateTab(tab);
      return;
    }

    const accordionTrigger = event.target.closest('[data-slot="accordion-trigger"]');
    if (accordionTrigger) syncAccordion(accordionTrigger);

    const dialogTrigger = event.target.closest(dialogTriggers);
    if (dialogTrigger) {
      const dialog = resolveDialog(dialogTrigger);
      if (dialog) {
        event.preventDefault();
        openDialog(dialog, dialogTrigger);
      }
      return;
    }

    const dialogCloseButton = event.target.closest(dialogClose);
    if (dialogCloseButton) {
      const dialog = dialogCloseButton.closest('dialog');
      if (dialog) {
        event.preventDefault();
        closeDialog(dialog);
      }
      return;
    }

    const toggle = event.target.closest('[data-slot="toggle-group-item"]');
    const toggleRoot = toggle?.closest(toggleGroups);
    if (toggleRoot && !toggle.disabled && toggle.getAttribute('aria-disabled') !== 'true') {
      event.preventDefault();
      const single = (toggleRoot.getAttribute('data-type') || 'multiple') === 'single';
      const on = toggle.getAttribute('data-state') === 'on';
      if (single) toggleRoot.querySelectorAll('[data-slot="toggle-group-item"]').forEach((item) => setToggleItem(item, false));
      setToggleItem(toggle, !on);
      syncToggleGroup(toggleRoot);
      return;
    }

    const calendar = event.target.closest(calendarRoot);
    if (calendar) {
      if (event.target.closest('[data-slot="calendar-prev"]')) {
        event.preventDefault();
        shiftCalendarMonth(calendar, -1);
        return;
      }
      if (event.target.closest('[data-slot="calendar-next"]')) {
        event.preventDefault();
        shiftCalendarMonth(calendar, 1);
        return;
      }
      const day = event.target.closest(calendarDayButton);
      if (day && !day.disabled) {
        calendar.setAttribute('data-selected', day.getAttribute('data-date'));
        syncCalendar(calendar);
        const picker = calendar.closest(datePickerRoot);
        if (picker) {
          picker.setAttribute('data-value', day.getAttribute('data-date'));
          const input = picker.querySelector('input[type="hidden"]');
          if (input) input.value = day.getAttribute('data-date');
        }
        return;
      }
    }

    const carouselPrevious = event.target.closest('[data-slot="carousel-previous"]');
    const carouselNext = event.target.closest('[data-slot="carousel-next"]');
    const carousel = (carouselPrevious || carouselNext)?.closest(carouselRoot);
    if (carousel) {
      event.preventDefault();
      moveCarousel(carousel, carouselNext ? 1 : -1);
      return;
    }

    const toastClose = event.target.closest('[data-slot="toast-close"]');
    const toast = toastClose?.closest(toastRoot);
    if (toast) {
      event.preventDefault();
      closeToast(toast);
      return;
    }

    const sidebarTrigger = event.target.closest('[data-slot="sidebar-trigger"]');
    const sidebar = sidebarTrigger?.closest(sidebarProvider);
    if (sidebar) {
      event.preventDefault();
      setSidebar(sidebar, sidebar.getAttribute('data-open') !== 'true');
      return;
    }

    const dateDay = event.target.closest('[data-slot="date-picker"] [data-slot="calendar-day-button"]');
    const datePicker = dateDay?.closest(datePickerRoot);
    if (datePicker && !dateDay.disabled) {
      const value = dateDay.getAttribute('data-date');
      datePicker.setAttribute('data-value', value);
      const input = datePicker.querySelector('input[type="hidden"]');
      if (input) input.value = value;
      return;
    }

    const clickedDialog = event.target.closest('dialog');
    if (clickedDialog && event.target === clickedDialog && clickedDialog.open) {
      closeDialog(clickedDialog);
      return;
    }

    const trigger = event.target.closest('[data-slot$="-trigger"], [data-dropdown-menu-trigger], [aria-haspopup]');
    const root = trigger?.closest(floatingRoots);
    if (root) {
      if (root.matches('[data-slot="tooltip"], [data-slot="hover-card"]')) return;
      event.preventDefault();
      openFloatingRoots().forEach((openRoot) => {
        if (openRoot !== root) setOpen(openRoot, false);
      });
      setOpen(root, !isOpen(root), trigger);
      if (isOpen(root) && root.matches(selectableRoots)) moveItemFocus(root, 1);
      return;
    }

    const item = event.target.closest('[data-slot$="-item"], [data-dropdown-menu-item]');
    const selectRoot = item?.closest('[data-slot="select"], [data-slot="combobox"]');
    if (item && selectRoot) {
      const value = item.getAttribute('data-value') || item.textContent.trim();
      selectRoot.setAttribute('data-value', value);
      selectRoot.querySelectorAll(selectableItems).forEach((option) => {
        const selected = option === item;
        option.setAttribute('aria-selected', selected ? 'true' : 'false');
        option.setAttribute('data-state', selected ? 'checked' : 'unchecked');
      });
      const display = selectRoot.querySelector('[data-slot$="-value"]');
      if (display) display.textContent = item.textContent.trim();
      const name = selectRoot.getAttribute('data-name');
      if (name) {
        let input = selectRoot.querySelector('input[type="hidden"][name="' + CSS.escape(name) + '"]');
        if (!input) {
          input = document.createElement('input');
          input.type = 'hidden';
          input.name = name;
          selectRoot.appendChild(input);
        }
        input.value = value;
        input.dispatchEvent(new Event('input', { bubbles: true }));
        input.dispatchEvent(new Event('change', { bubbles: true }));
      }
      setOpen(selectRoot, false);
    }

    openFloatingRoots().forEach((openRoot) => {
      if (!openRoot.contains(event.target)) setOpen(openRoot, false);
    });
  });

  document.addEventListener('input', (event) => {
    const input = event.target.closest(commandInput);
    const root = input?.closest(commandRoot);
    if (root) filterCommand(root, input.value);
    const sliderInput = event.target.closest('[data-slot="slider"] input[type="range"]');
    const slider = sliderInput?.closest(sliderRoots);
    if (slider) syncSlider(slider);
    const otpSlot = event.target.closest('[data-slot="input-otp-slot"]');
    const otp = otpSlot?.closest(inputOTPRoot);
    if (otp) syncOTP(otp);
  });

  document.addEventListener('change', (event) => {
    const radio = event.target.closest('[data-slot="radio-group-item"] input[type="radio"]');
    const radioRoot = radio?.closest(radioGroups);
    if (radioRoot) syncRadioGroup(radioRoot);
    const checked = event.target.closest(checkedInputs);
    if (checked) syncCheckedInput(checked);
  });

  document.addEventListener('mouseover', openHoverFloating);
  document.addEventListener('mouseout', closeHoverFloating);
  document.addEventListener('focusin', openHoverFloating);
  document.addEventListener('pointerdown', startResizableDrag);

  document.addEventListener('keydown', (event) => {
    const command = event.target.closest(commandRoot);
    if (command) {
      if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
        event.preventDefault();
        moveItemFocus(command, event.key === 'ArrowDown' ? 1 : -1);
        return;
      }
      if (event.key === 'Enter') {
        const item = event.target.closest(commandItem) || command.querySelector(commandItem + '[data-highlighted]');
        if (item && !item.hidden && !item.disabled && item.getAttribute('aria-disabled') !== 'true') {
          event.preventDefault();
          item.click();
          return;
        }
      }
    }

    const tab = event.target.closest('[data-slot="tabs-trigger"]');
    if (tab) {
      const tabsRoot = tab.closest('[data-slot="tabs"], [data-tabs-root]');
      const tabs = tabsRoot ? enabledTabs(tabsRoot) : [];
      const current = tabs.indexOf(tab);
      let next = -1;
      if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = (current + 1) % tabs.length;
      else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = (current - 1 + tabs.length) % tabs.length;
      else if (event.key === 'Home') next = 0;
      else if (event.key === 'End') next = tabs.length - 1;
      else if (event.key === 'Enter' || event.key === ' ') next = current;
      if (tabsRoot && current >= 0 && next >= 0) {
        event.preventDefault();
        tabs[next].focus();
        activateTab(tabs[next]);
        return;
      }
    }

    const accordionTrigger = event.target.closest('[data-slot="accordion-trigger"]');
    if (accordionTrigger) {
      const accordionRoot = accordionTrigger.closest('[data-slot="accordion"]');
      const triggers = accordionRoot ? Array.from(accordionRoot.querySelectorAll('[data-slot="accordion-trigger"]')).filter((trigger) => trigger.getAttribute('aria-disabled') !== 'true') : [];
      const current = triggers.indexOf(accordionTrigger);
      let next = -1;
      if (event.key === 'ArrowDown') next = (current + 1) % triggers.length;
      else if (event.key === 'ArrowUp') next = (current - 1 + triggers.length) % triggers.length;
      else if (event.key === 'Home') next = 0;
      else if (event.key === 'End') next = triggers.length - 1;
      if (current >= 0 && next >= 0) {
        event.preventDefault();
        triggers[next].focus();
        return;
      }
    }

    const dialog = document.querySelector('dialog[open]');
    if (dialog) {
      if (event.key === 'Escape') {
        event.preventDefault();
        closeDialog(dialog);
        return;
      }
      if (event.key === 'Tab' && dialog.getAttribute('data-modal') !== 'false') {
        const nodes = focusable(dialog);
        if (!nodes.length) return;
        const first = nodes[0];
        const last = nodes[nodes.length - 1];
        if (event.shiftKey && document.activeElement === first) {
          event.preventDefault();
          last.focus();
        } else if (!event.shiftKey && document.activeElement === last) {
          event.preventDefault();
          first.focus();
        }
      }
    }

    const rootCandidate = event.target.closest(floatingRoots);
    const root = rootCandidate?.getAttribute('data-open') === 'true' ? rootCandidate : null;
    const selectTrigger = event.target.closest('[data-slot="select-trigger"], [data-slot="combobox-trigger"]');
    const selectRoot = selectTrigger?.closest(selectableRoots);
    if (!root && selectRoot && ['ArrowDown', 'ArrowUp', 'Enter', ' '].includes(event.key)) {
      event.preventDefault();
      openFloatingRoots().forEach((openRoot) => {
        if (openRoot !== selectRoot) setOpen(openRoot, false);
      });
      setOpen(selectRoot, true, selectTrigger);
      moveItemFocus(selectRoot, event.key === 'ArrowUp' ? -1 : 1);
      return;
    }
    if (event.key === 'Escape') {
      const openRoot = root || openFloatingRoots()[0];
      if (openRoot) {
        event.preventDefault();
        setOpen(openRoot, false);
      }
    }
    if (root && (event.key === 'ArrowDown' || event.key === 'ArrowUp')) {
      event.preventDefault();
      moveItemFocus(root, event.key === 'ArrowDown' ? 1 : -1);
    } else if (root && (event.key === 'Enter' || event.key === ' ')) {
      const item = event.target.closest(selectableItems);
      if (item) {
        event.preventDefault();
        item.click();
      }
    } else if (root?.matches(selectableRoots) && event.key.length === 1 && !event.metaKey && !event.ctrlKey && !event.altKey) {
      focusByTypeahead(root, event.key);
    }
  });

  window.addEventListener('resize', () => openFloatingRoots().forEach(positionFloating));
  window.addEventListener('scroll', () => openFloatingRoots().forEach(positionFloating), true);
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initRuntime, { once: true });
else initRuntime();
`
}
